services:
  - type: web
    name: codearena
    env: python
    rootDir: django_app
    buildCommand: pip install -r ../requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn codearena.wsgi:application
