# Generated by Django 6.1 on 2026-08-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('starter_code', models.TextField(blank=True, default='# Write your solution below\n')),
                ('sample_input', models.TextField(blank=True, help_text='Fed to the program via stdin')),
                ('sample_output', models.TextField(blank=True, help_text='Expected stdout (compared after trimming whitespace)')),
            ],
        ),
    ]
